##
# Ansible playbook that uses the PostgreSQL module.
#
# This installs PostgreSQL on an Ubuntu system, creates a database called
# "{{ dbname }}" and a user called "{{ dbuser }}" with password "{{ pwd }}"
# with access to the "{{ dbname }}" database.
#
---
- hosts: '{{ hosts }}'
  sudo: yes
  gather_facts: no

  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

- hosts: '{{ hosts }}' 
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  vars_prompt:
    - name: "dbname"
      prompt: "Database name?"
      private: no

    - name: "dbuser"
      prompt: "Database user name?"
      private: no

    - name: "dbpassword"
      prompt: "Database user password?" 
      private: yes

  tasks:
  - name: create database user
    postgresql_user: name={{dbuser}} password={{dbpassword}}

  - name: ensure database is created
    postgresql_db: name={{dbname}}
                   encoding='UTF-8'
                   template='template0'
                   owner={{dbuser}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}}

  - name: ensure user does not have unnecessary privilege
    postgresql_user: user={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
